### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by Mansaylon** [Digitalroot-Valheim/Digitalroot.Valheim.GoldBars#2]
### Problem

Sorry ... but unfortunately I have not found a place where I could put my problem with your mod.
And under discussion I couldn't ask a question.

Since version 1.1.1 I get a message when starting the game (client) that the necessary mod is not installed on the server. Unfortunately, all attempts to get the mod to work on the server have failed.
And so I can no longer join my server.

### Solution

I hope you will forgive me that I was looking for contact via this path .... but also in Nexuxmods I could not find any opportunity for discussion.

### Screenshots

![modserver2](https://user-images.githubusercontent.com/66419502/132372883-680eff5f-2908-44f2-a109-9cfdf1cc5e12.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Digitalroot** [comment]
Do you have control of of the server?

**Comment by Mansaylon** [comment]
Yes. It is a Linux CentOS 8 Server

https://inaktiv.ch/files/yggdrasil.txt

**Comment by Digitalroot** [comment]
It looks like you do not have any mods loading on the server at all. Look at [BepInExPack_Valheim](https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/) for info on how to get BepInEx to work on a Linux server. Also checkout the [Valheim Discord](https://discord.gg/valheim), there are channels for server help. Also checkout the [Valheim Mod Discord](https://discord.gg/FfQfU38Z)

**Comment by Mansaylon** [comment]
I've already recognized that much ;-)

BepInEx is installed on the server. I also start server_start_bepinex.sh with the correct server data. Still, no mod wants to start on the server side.

Since from September 16 after the master update, many mods will probably no longer run, I'll wait and see.

**Comment by Digitalroot** [comment]
This mod has a release that makes it work with HnH.
