### ISSUE TITLE
[Feature]: Other placeable ignots

### ISSUE THREAD

**Issue by GamingHQ** [Digitalroot-Valheim/Digitalroot.Valheim.GoldBars#3]
### Problem

Good morning.

My apologies for not being able to place anything in discussions. This however is due to the fact the only owners of a repository can open one where others can reply towards.

I have an idea, but I don't know if this would be possible. Would it be an option to add the ability to place unused ingots as well? iron, copper, black metal, and such, or would there be already such mod? I'm new to valheim, so I don't know much about trustworthy websites besides nexus mods. 

happy weekend wishes and please, stay safe!

### Solution

-

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Digitalroot** [comment]
> My apologies for not being able to place anything in discussions. This however is due to the fact the only owners of a repository can open one where others can reply towards.

Thank you for letting me know. I'll have to fix that.
